// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VafUIClient is the client API for VafUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VafUIClient interface {
	// ListFunctionSpecs returns a list of Service Function(s) that can be started through the UI.
	ListFunctionSpecs(ctx context.Context, in *ListFunctionSpecsRequest, opts ...grpc.CallOption) (VafUI_ListFunctionSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type vafUIClient struct {
	cc grpc.ClientConnInterface
}

func NewVafUIClient(cc grpc.ClientConnInterface) VafUIClient {
	return &vafUIClient{cc}
}

func (c *vafUIClient) ListFunctionSpecs(ctx context.Context, in *ListFunctionSpecsRequest, opts ...grpc.CallOption) (VafUI_ListFunctionSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VafUI_ServiceDesc.Streams[0], "/v1.VafUI/ListFunctionSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &vafUIListFunctionSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VafUI_ListFunctionSpecsClient interface {
	Recv() (*ListFunctionSpecsResponse, error)
	grpc.ClientStream
}

type vafUIListFunctionSpecsClient struct {
	grpc.ClientStream
}

func (x *vafUIListFunctionSpecsClient) Recv() (*ListFunctionSpecsResponse, error) {
	m := new(ListFunctionSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vafUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.VafUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VafUIServer is the server API for VafUI service.
// All implementations must embed UnimplementedVafUIServer
// for forward compatibility
type VafUIServer interface {
	// ListFunctionSpecs returns a list of Service Function(s) that can be started through the UI.
	ListFunctionSpecs(*ListFunctionSpecsRequest, VafUI_ListFunctionSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedVafUIServer()
}

// UnimplementedVafUIServer must be embedded to have forward compatible implementations.
type UnimplementedVafUIServer struct {
}

func (UnimplementedVafUIServer) ListFunctionSpecs(*ListFunctionSpecsRequest, VafUI_ListFunctionSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFunctionSpecs not implemented")
}
func (UnimplementedVafUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedVafUIServer) mustEmbedUnimplementedVafUIServer() {}

// UnsafeVafUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VafUIServer will
// result in compilation errors.
type UnsafeVafUIServer interface {
	mustEmbedUnimplementedVafUIServer()
}

func RegisterVafUIServer(s grpc.ServiceRegistrar, srv VafUIServer) {
	s.RegisterService(&VafUI_ServiceDesc, srv)
}

func _VafUI_ListFunctionSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFunctionSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VafUIServer).ListFunctionSpecs(m, &vafUIListFunctionSpecsServer{stream})
}

type VafUI_ListFunctionSpecsServer interface {
	Send(*ListFunctionSpecsResponse) error
	grpc.ServerStream
}

type vafUIListFunctionSpecsServer struct {
	grpc.ServerStream
}

func (x *vafUIListFunctionSpecsServer) Send(m *ListFunctionSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VafUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VafUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VafUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VafUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VafUI_ServiceDesc is the grpc.ServiceDesc for VafUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VafUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VafUI",
	HandlerType: (*VafUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _VafUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFunctionSpecs",
			Handler:       _VafUI_ListFunctionSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vaf-ui.proto",
}
